upload:
	cp *.h5 /eos/home-l/lcoyle/obsbox_metadata/
	cp no_data.json /eos/home-l/lcoyle/obsbox_metadata/

download:
	curl https://cernbox.cern.ch/index.php/s/o4kx7E6XTIdRbwE/download | tar -xz

.PHONY: download upload
